#!/bin/sh
#
# (c) 2007, by Robert Manea

OPTS='-bg #323232 -fg #5FBF77 -p -l 20 -e onstart=uncollapse,scrollhome;button5=scrolldown;key_Down=scrolldown;button4=scrollup;key_Up=scrollup;key_Page_Down=scrolldown:20;key_Page_Up=scrollup:20;key_Escape=exit;button3=exit;entertitle=grabkeys;enterslave=grabkeys;leaveslave=ungrabkeys'

if [ -e ./dzen2 ]; then
	(echo "^#323232^#5FBF77Documentation (use: scrollwheel, arrow keys, PgUP/PgDown to scroll. Escape or mouse button3 to exit)"; cat README) | ./dzen2 $OPTS
else
	echo "Please type 'make' to build dzen and rerun help"
fi
